#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, SELECTOR, BRING_TO_FRONT, SEND_TO_BACK, PLUS, MINUS};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, CLEAR};

#endif